blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/ExistentialAudio/WhiteHole/discussions
    about: Suggest an idea for a new feature.
  - name: I need help setting up or troubleshooting WhiteHole
    url: https://github.com/ExistentialAudio/WhiteHole/discussions
    about: Questions about how to configure your favorite apps.
